site_name: Robots10x Wiki
site_url: https://qut-robotics-club.github.io/robot-docs
repo_url: https://github.com/qut-robotics-club/robot-docs
repo_name: qut-robotics-club/robot-docs
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - toc.follow
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tooltips

nav:
  - Home: index.md
  - Robots101:
      - robots101/index.md
  - Robots102:
      - robots102/00-index.md
      # basics: 0x-title.md
      # intermediate: 1x-title.md
      # ROS: 2x-title.md
      # advanced: 3x-title.md
      - Command Line Basics: robots102/01-command-line-basics.md
      - Git Basics: robots102/02-version-control.md
      - Project Management: robots102/03-project-management.md
      - Interfacing with Hardware: robots102/hardware-interfacing.md
      - Intermediate Linux: robots102/10-intermediate-linux.md
      - Installing ROS: robots102/install-ros.md
      - ROS with Python: robots102/ros-py.md
      - ROS with C++: robots102/ros-cpp.md
  - Resources:
      - resources/index.md
      - Setting up new Pi's: resources/pi-setup.md
      - Network Config: resources/network-setup.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.tilde
  - toc:
      permalink: true

watch:
  - includes
